name: Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build_and_push:
    name: Build, Tag, and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # - name: Install Docker Compose
      #   run: sudo apt-get update && sudo apt-get install -y docker-compose

      # - name: Start Application with Docker Compose
      #   run: docker-compose up --build -d

  sonar:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    needs: build_and_push # Run after the Docker build is complete

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        with:
          args: >
            -Dsonar.projectKey=kRehman007_EduLearn_-MERN-
            -Dsonar.organization=krehman007
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.exclusions="**/node_modules/**,**/*.test.js,**/dist/**"
            -Dsonar.sourceEncoding=UTF-8

  zap_scan:
    name: OWASP ZAP Security Scan
    runs-on: ubuntu-latest
    needs: sonar # Run after SonarQube analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: OWASP ZAP Scan
        run: |
          docker run --network="host" -t ghcr.io/zaproxy/zaproxy zap-baseline.py \
            -t http://172.17.0.1:5001 \  # ✅ Replace with your backend's base URL
            -r zap_report.html \
            -I -l WARN -T 5

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4 # ✅ Updated to v4
        with:
          name: zap-security-report
          path: zap_report.html
